name: Test Http Code

on: 
  workflow_dispatch:
    inputs:
      url: 
        description: "Chose an url"
        required: true
        default: "https://github.com/"
        type: choice
        options:
          - "https://github.com/"
          - "https://www.google.com/?hl=es"
      os:
        description: "Os"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          -  "ubuntu-latest"
          -  "windows-latest"
          -  "macos-latest"

jobs:
  test:
    runs-on: ${{github.event.inputs.os}}

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: http test
      run: |
        mkdir log-folder
        curl -s -o /dev/null -w "%{http_code}\n" ${{github.event.inputs.url}} 2>&1 | tee log-folder/log.txt

    - name: upload log
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: log-folder

    
