name: Test

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Do you want to start this project ?"
        required: true
        default: "no"
        type: choice
        options:
          - "no"
          - "yes"
      node_version:
        description: "Chose Node version"
        required: true
        default: "17"
        type: choice
        options:
          - "17"
          - "18"
          - "19"
          - "20"
      os:
        description: "CHose  Os System"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - "ubuntu-latest"
          - "windows-latest"
          
jobs:
  build:
    if: ${{github.event.inputs.start == 'yes'}}
    runs-on: ${{github.event.inputs.os}} 

    steps:
    - name: Ceckout Code
      uses: actions/checkout@v2

    - name: Setup Node version
      uses: actions/setup-node@v2
      with:
        node-version: "${{github.event.inputs.node_version}}"

    - name: download artifact
      run: |
        mkdir test-folder
        echo "hola" > test-folder/log.txt
    
    - name: install dependencies
      run: |
        npm install 2>&1 | tee test-log.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{github.event.inputs.os}}
        path: test-folder
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: test-log.txt
