name: Test

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "Cual es tu nombre ?"
        required: true
        default: "Thiago"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node Js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        echo "Nombre: ${{github.event.inputs.nombre}}"
        npm install
