name: Test

on:
  workflow_dispatch:
    inputs:
      nombre:
        description: "cual es tu nombre ?"
        required: true
        default: "Thaigo"
        type: choice
        options:
            - Thiago
            - T
            - Qa
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node Js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      if: ${{github.event.inputs.nombre == 'T'}}
      run: |
        echo "Nombre: ${{github.event.inputs.nombre}}"
        npm install
