name: test

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node Version"
        required: true
        default: "18"
        type: choice
        options:
          - "18"
          - "19"
          - "20"
      environment:
        description: "Chose your enivronment"
        required: true
        default: "qa"
        type: choice
        options:
          - "qa"
          - "dev"
      os:
        description: "Chose your enivronment"
        required: true
        default: "windows-latest"
        type: choice
        options:
          - "windows-latest"
          - "ubuntu-latest"
jobs:
  build:
    if: ${{github.event.inputs.environment == 'qa'}}
    runs-on: ${{github.event.inputs.os}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: "${{github.event.inputs.node_version}}"

    - name: create logs
      run: |
        mkdir test-folder
        echo "logs" > test-folder/log.txt
    
    - name: upload artifacts x1
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: test-folder

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: install dependencies
      run: |
        mkdir node
        npm install 2>&1 | tee node/node_log.txt


    - name: upload artifacts x2
      uses: actions/upload-artifact@v4
      with:
        name: NodeJs
        path: node
